# Generated by Django 4.0.3 on 2022-04-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Friend',
        ),
    ]
