# Generated by Django 4.0.3 on 2022-04-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_friend_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='school',
            field=models.CharField(choices=[('I LOVE UT', 1), ('I hate it (I got rejected)', 0)], default='I LOVE UT', max_length=120),
        ),
    ]
