# Generated by Django 4.0.3 on 2022-04-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_friend_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='school',
            field=models.CharField(default='I LOVE UT', max_length=20),
        ),
    ]
