# Generated by Django 4.0.3 on 2022-04-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_friend_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='winner',
            field=models.CharField(blank=True, default='UT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='school',
            field=models.CharField(default='UT', max_length=20),
        ),
    ]
