# Generated by Django 4.0.3 on 2022-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_friend_winner_alter_friend_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='winner',
        ),
        migrations.AddField(
            model_name='friend',
            name='best_school',
            field=models.CharField(default='UT', max_length=20),
        ),
    ]
