# Generated by Django 4.0.3 on 2022-04-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_remove_friend_best_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='best_school',
            field=models.CharField(default='UT', max_length=20),
        ),
    ]
